FROM scratch

LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.description="Combine multiple Prometheus textformat inputs into one"

WORKDIR /

COPY LICENSE README.md /
COPY prometheus-textformat-merge /

ENTRYPOINT ["/prometheus-textformat-merge"]

# vim: set ft=dockerfile :
