# Configuration for GoReleaser
# https://goreleaser.com/

version: 2

project_name: prometheus-textformat-merge

builds:
  - main: .
    binary: prometheus-textformat-merge
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath

nfpms:
  - description: Utility to merge Prometheus textformat files
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/prometheus-textformat-merge/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/prometheus-textformat-merge/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

changelog:
  groups:
    - title: Dependencies
      regexp: '(?i)^(?:[a-f0-9]{8,64}\s+)?Bump\s+[-.\w]+/\w.*\sto\s'
      order: 1
    - order: 0

release:
  draft: true
  prerelease: auto

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
