# Configuration for GoReleaser
# https://goreleaser.com/

version: 2

project_name: prometheus-textformat-merge

builds:
  - main: .
    binary: prometheus-textformat-merge
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath

nfpms:
  - description: Utility to merge Prometheus textformat files
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/prometheus-textformat-merge/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/prometheus-textformat-merge/LICENSE

archives:
  - formats:
      - tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        formats:
          - zip

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: contrib/Dockerfile.goreleaser
    extra_files: &docker_extra_files
      - LICENSE
      - README.md
    image_templates:
      - ghcr.io/hansmi/prometheus-textformat-merge:{{.Tag}}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: contrib/Dockerfile.goreleaser
    extra_files: *docker_extra_files
    image_templates:
      - ghcr.io/hansmi/prometheus-textformat-merge:{{.Tag}}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}

docker_manifests:
  - name_template: ghcr.io/hansmi/prometheus-textformat-merge:{{.Tag}}
    image_templates: &docker_manifest_image_templates
      - ghcr.io/hansmi/prometheus-textformat-merge:{{.Tag}}-amd64
      - ghcr.io/hansmi/prometheus-textformat-merge:{{.Tag}}-arm64
  - name_template: ghcr.io/hansmi/prometheus-textformat-merge:v{{.Major}}
    image_templates: *docker_manifest_image_templates
  - name_template: ghcr.io/hansmi/prometheus-textformat-merge:latest
    image_templates: *docker_manifest_image_templates

changelog:
  groups:
    - title: Dependencies
      regexp: '(?i)^(?:[a-f0-9]{8,64}\s+)?Bump\s+[-.\w]+/\w.*\sto\s'
      order: 1
    - order: 0

release:
  draft: true
  prerelease: auto

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
