name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron:  '35 15 * * 1'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: 1

      - uses: actions/cache@v2
        with:
          # https://github.com/actions/cache/blob/main/examples.md#go---modules
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Dependencies
        run: go get -v

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

# vim: set sw=2 sts=2 et : -->
